# Generated by Django 4.0.3 on 2022-04-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0003_alter_artigo_options_alter_artigo_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='artigo',
            managers=[
            ],
        ),
    ]
