# Generated by Django 4.0.3 on 2022-06-29 19:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0005_categoria_artigo_imagem_alter_artigo_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-criado'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Contéudo'),
        ),
    ]
